"""update tasks model

Revision ID: ac0d45245c06
Revises: 7e9b0cbebfcc
Create Date: 2025-12-04 10:49:41.418113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac0d45245c06'
down_revision = '7e9b0cbebfcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=False))
        batch_op.create_index(batch_op.f('ix_task_due_date'), ['due_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_due_date'))
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###
